ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.hadar.HttpKt.configureHttp
      com.hadar.SerializationKt.configureSerialization
      com.hadar.SecurityKt.configureSecurity
      com.hadar.WebsocketsKt.configureWebsockets
      com.hadar.RateLimitingKt.configureRateLimiting
      com.hadar.MongoKt.configureMongo
      com.hadar.StatusPagesKt.configureStatusPages
      com.hadar.SseKt.configureSse
      com.hadar.RoutingKt.configureRouting
    ]
  }
}